#!/usr/bin/env bash

FONT="-fn JetBrains Mono 11"
COLORS="-nb #1f1d2e -nf #e0def4 -sb #eb6f92 -sf #21202e"

command=$(docker container ls -a --format='{{ .ID}} {{ .Names}} {{ .Status}}')
lines=$(wc -l <<< $command)

selected="$(echo "$command" | \
  rofi -dmenu -i -p "Select container to toggle: " \
  -l $lines $COLORS $FONT | \
  awk '{print $1, $2, $3}' )";

if [[ ! -z $selected ]]; then
  answer="$(echo -e "Yes\nNo" | \
    rofi -dmenu -i -p "$(awk '{print $2}'<<< $selected) will be toggle, are you sure?" \
    -l 2 $COLORS $FONT )"

  if [[ $answer == "Yes" ]]; then
    containerId="$(awk '{print $1}' <<< $selected)";
    if [[ $(awk '{print $3}' <<< $selected) == "Up" ]]; then
      docker stop $containerId
    else
      docker start $containerId
    fi
  fi
fi

exit 0
