#! /bin/sh

uptime="`uptime -p | sed -e 's/up //g'`"

variants=$(printf " Power Off\n Restart\n" | rofi -dmenu -i \
  -theme-str '@import "rosepine_powermenu.rasi"' \
	-mesg "Uptime: $uptime" \
)

case "$variants" in
	"  Power Off") poweroff ;;
	"  Restart") reboot ;;
  *) exit 1 ;;
esac
